### ISSUE TITLE
Error while converting model to tensorflow lite

### ISSUE THREAD

**Issue by hahmad2008** [abdelrahman-gaber/tf2-object-detection-api-tutorial#1]
Thank you, Abdelrahman, so much for the well-organized tutorial, I really spent time searching for good tutorials for object detection and up to date. 

I had successfully train and test the model as you explained, but when I tried to convert it to tensorflow lite, I got the following error:
Could you please help me?

`tflite_convert \
  --saved_model_dir=models/ssd_mobilenet_v2_raccoon/exported_model/saved_model \
  --output_file=models/ssd_mobilenet_v2_raccoon/ssd_mobilenet_v2_raccoon.tflite`

I got this error:

> 2020-08-05 10:19:30.217661: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:799]   constant_folding: Graph size after: 1394 nodes (0), 2116 edges (0), time = 77.785ms.
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/v_python3.6/bin/tflite_convert", line 8, in <module>
>     sys.exit(main())
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 638, in main
>     app.run(main=run_main, argv=sys.argv[:1])
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 621, in run_main
>     _convert_tf2_model(tflite_flags)
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/tensorflow/lite/python/tflite_convert.py", line 237, in _convert_tf2_model
>     tflite_model = converter.convert()
>   File "/opt/anaconda3/envs/v_python3.6/lib/python3.6/site-packages/tensorflow/lite/python/lite.py", line 483, in convert
>     _get_tensor_name(tensor), shape_list))
> ValueError: None is only supported in the 1st dimension. Tensor 'input_tensor' has invalid shape '[1, None, None, 3]'.

**Comment by a64bit** [comment]
Hi @hahmad2008  .. I did not try tf_lite with TF2 before, but will look at it this weekend.
Meanwhile, can you check this solution: https://github.com/tensorflow/tensorflow/issues/22564#issuecomment-425515540

**Comment by hahmad2008** [comment]
@abdelrahman-gaber Thank you! I tried to convert the checkpoint (saved_model) using this [solution](https://colab.research.google.com/gist/jvishnuvardhan/23066f1a722fc566b437a5210d1b97b0/ssd_saved_model_tflite_conversion.ipynb#scrollTo=X5s5D5ufCcKb), it is successfully converted but I think it is incorrect since I checked the input for the model I got it as [1,1,1,3] instead of [1,300,300,3]

I use this directory 
![image](https://user-images.githubusercontent.com/68266028/89432198-7ee8ec80-d749-11ea-93b1-ad8c0803fe81.png)

**Comment by hahmad2008** [comment]
what type of model you generated in the exported_model/saved_model 
is it a saved or frozen model?

**Comment by a64bit** [comment]
In the exported_model/saved_model, it is saved models. It is the same as all models in the [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md).
I think we should use the saved model in TF2 instead of frozen graphs. refer to this [thread](https://github.com/tensorflow/tensorflow/issues/27614) for more information. But there are some ways to freeze the model as mentioned in the thread, and also [here](https://leimao.github.io/blog/Save-Load-Inference-From-TF2-Frozen-Graph/).

**Comment by hahmad2008** [comment]
Thank you @abdelrahman-gaber 
have you had a chance to convert the model to TensorFlow lite?

**Comment by a64bit** [comment]
@hahmad2008 Can you please try [this](https://colab.research.google.com/gist/abdelrahman-gaber/d010131163375f2bd0379fbd4523aa68/ssd_saved_model_tflite_conversion.ipynb).
This solution is working on colab with the newest tensorflow nightly version, but not working on my machine with Tensoflow 2.2.0 and giving me errors. Please confirm if the output model is working with you, and then we can check the TF version which works best.

**Comment by hahmad2008** [comment]
Thank you @abdelrahman-gaber 
I also tried [this solution](https://github.com/tensorflow/tensorflow/issues/42114#issuecomment-671593386) it works as well. 

But I am trying to test the tflite model. could u please check that?

**Comment by a64bit** [comment]
@hahmad2008 Great. It is basically the same solution I tried in the colab, but it will need tensorlfow version higher than 2.2.0
Anyways, I will check exactly what is the minimum version required and let you know about that. 

To test the tflie model, you should use the [tflite interpreter](https://www.tensorflow.org/lite/guide/inference) .. I will try to make some instructions for tflite conversion and inference in the tutorial, I think it maybe helpful.

**Comment by hahmad2008** [comment]
Thanks, @abdelrahman-gaber . No need. I tried the following and it works :D 

![image](https://user-images.githubusercontent.com/68266028/90097057-bd7c3980-dd3d-11ea-8a25-39540e6897bb.png)

**Comment by a64bit** [comment]
Great! So maybe you can share your complete solution here for anyone who will face this issue in the future 🙏

**Comment by hahmad2008** [comment]
@abdelrahman-gaber Ya sure!

**Comment by hahmad2008** [comment]
For testing TFLITE model on images check this code:
[LINK](https://github.com/EdjeElectronics/TensorFlow-Lite-Object-Detection-on-Android-and-Raspberry-Pi/blob/master/TFLite_detection_image.py)
