### ISSUE TITLE
Calculations in train_labels.csv

### ISSUE THREAD

**Issue by magedhelmy1** [abdelrahman-gaber/tf2-object-detection-api-tutorial#2]
The calculations in your -> tf2-object-detection-api-tutorial/data/raccoon_data/train_labels.csv do not add up.

Take the first line for example

```
width= 800 
height= 533
xmin= 105 
ymin=10 
xmax= 502 
ymax= 501
```

If your xmin=105 and your width is 800, then your xmax should be 905 and not 502.

Same for the y-axis,
if your ymin=10 and your height is 533 then your ymax should be 543 and not 501

Please correct me if I missed something.

**Comment by a64bit** [comment]
width and height are for the image size, not the box width and height. 
xmin, ymin, xmax, ymax are for the bounding boxes of the object as shown in this image

![image](https://user-images.githubusercontent.com/8361044/89533634-acf42c80-d82e-11ea-8102-b10222cd37de.png)
